def RUN_ID = ""

pipeline {

    agent any

    environment {

        PYTHON_ENV = 'venv'
    }

    stages {

        stage('Checkout Source Code') {

            steps {

                checkout scm
            }
        }

        stage('Verify Tooling') {

            steps {

                sh 'python3 --version'

                sh 'docker --version'

                sh 'kubectl version --client'
            }
        }

        stage('Create Virtual Environment') {

            steps {

                sh 'python3 -m venv ${PYTHON_ENV}'
            }
        }

        stage('Install Dependencies') {

            steps {

                sh '. ${PYTHON_ENV}/bin/activate && pip install -r requirements.txt'
            }
        }

        stage('Build Docker Image') {

            steps {

                sh 'docker build -t qe-control-plane:latest -f docker/Dockerfile .'
            }
        }

        stage('Execute Kubernetes Job') {

            steps {

                script {

                    sh """
                        export BUILD_TAG=${BUILD_TAG}
                        . ${PYTHON_ENV}/bin/activate
                        python -m scripts.execution.k8s_execution
                    """


                    def runId = readFile(file: 'run_id.txt').trim()

                    echo "Read RUN_ID from file: ${runId}"


                    RUN_ID = runId

                    echo "Captured RUN_ID: ${RUN_ID}"
                }
            }
        }

        stage('Archive Runtime Artifacts') {

            steps {

                archiveArtifacts(
                    artifacts: "artifacts/runs/${RUN_ID}/**/*",
                    fingerprint: true
                )
            }
        }

        stage('Publish Allure Report') {

            steps {

                allure(
                    includeProperties: false,
                    jdk: '',
                    results: [[path: "artifacts/runs/${RUN_ID}/allure-results"]]
                )
            }
        }

        stage('Publish JUnit Report') {

                steps {

                     sh "ls -R artifacts/runs/${RUN_ID}/junit || true"

                     junit "artifacts/runs/${RUN_ID}/junit/results.xml"
        }
}

    }

    post {

        always {

            cleanWs()
        }

        success {

            echo 'QE Control Plane pipeline executed successfully'
        }

        failure {

            echo 'QE Control Plane pipeline execution failed'
        }
    }
}