pipeline {

    agent any

    environment {

        RUN_ID = ""
    }

    stages {

        stage('Build Docker Image') {

            steps {

                sh 'docker build -t qe-control-plane:latest -f docker/Dockerfile .'
            }
        }

        stage('Execute Kubernetes Job') {

            steps {

                script {

                    def execution_output = sh(
                        script: 'python -m scripts.execution.k8s_execution',
                        returnStdout: true
                    ).trim()

                    echo execution_output


                    env.RUN_ID = sh(
                        script: """
                            echo "${execution_output}" | \
                            grep RUN_ID | tail -1 | cut -d '=' -f2
                        """,
                        returnStdout: true
                    ).trim()


                    echo "Captured RUN_ID: ${env.RUN_ID}"
                }
            }
        }

        stage('Archive Artifacts') {

            steps {

                archiveArtifacts artifacts: "artifacts/runs/${env.RUN_ID}/**/*"
            }
        }
    }

    post {

        always {

            junit "artifacts/runs/${env.RUN_ID}/junit/results.xml"
        }
    }
}