pipeline {

    agent any

    environment {

        PYTHON_ENV = 'venv'

        RUN_ID = ''
    }

    stages {

        stage('Checkout Source Code') {

            steps {

                checkout scm
            }
        }

        stage('Verify Tooling') {

            steps {

                sh 'python3 --version'

                sh 'docker --version'

                sh 'kubectl version --client'
            }
        }

        stage('Create Virtual Environment') {

            steps {

                sh 'python3 -m venv ${PYTHON_ENV}'
            }
        }

        stage('Install Dependencies') {

            steps {

                sh '. ${PYTHON_ENV}/bin/activate && pip install -r requirements.txt'
            }
        }

        stage('Build Docker Image') {

            steps {

                sh 'docker build -t qe-control-plane:latest -f docker/Dockerfile .'
            }
        }

        stage('Execute Kubernetes Job') {

                 steps {

                     script {

                            def execution_output = sh(
                            script: '. ${PYTHON_ENV}/bin/activate && python -m scripts.execution.k8s_execution',
                            returnStdout: true
                     ).trim()


                    echo execution_output


                    env.RUN_ID = execution_output
                    .split("\\n")
                    .find { it.startsWith("RUN_ID=") }
                    .split("=")[1]
                    .trim()
                echo "Captured RUN_ID: ${env.RUN_ID}"
                }
             }
        }

        stage('Archive Runtime Artifacts') {

            steps {

                archiveArtifacts(
                    artifacts: "artifacts/runs/${env.RUN_ID}/**/*",
                    fingerprint: true
                )
            }
        }

        stage('Publish Allure Report') {

            steps {

                allure(
                    includeProperties: false,
                    jdk: '',
                    results: [[path: "artifacts/runs/${env.RUN_ID}/allure-results"]]
                )
            }
        }
    }

    post {

        always {

            junit "artifacts/runs/${env.RUN_ID}/junit/results.xml"

            cleanWs()
        }

        success {

            echo 'QE Control Plane pipeline executed successfully'
        }

        failure {

            echo 'QE Control Plane pipeline execution failed'
        }
    }
}